language: android
sudo: required
dist: precise
jdk:
 - oraclejdk8
android:
  components:
    # View the full list of Android SDK Tools by running
    #android list sdk --no-ui --all --extended

    # Make sure that the latest tools are available
    - tools
    # The above triggers an update to the repo, but might not install
    # the latest version of the tools. We need the latest emulator
    # no matter what, so trigger another update to be absolutely sure
    - tools
    - platform-tools

    # Please try to keep these versions in sync with build.gradle
    - platform-tools-24.0.3
    - build-tools-24.0.3

    # Need to include a platform for android.compileSdkVersion
    - android-24
    # Plus one for the emulator
    - android-21

    # Required for android wear (unused by mobile and tv)
    - extra-google-google_play_services
    # Required for android wear. Credit to http://stackoverflow.com/a/40083710
    - extra-google-m2repository
    # Needed for support library
    - extra-android-m2repository
    - addon-google_apis-google-24

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
# Emulator setup
before_script:
  - echo no | android create avd --force -n test21 -t android-21 --abi armeabi-v7a
  # You must specify an avd when requesting emulator version info
  - emulator -avd test21 -version
  - emulator -avd test21 -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
# Gradle caches more than Travis likes
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/